# Generated by Django 2.2.24 on 2024-03-03 13:19

from django.db import migrations
import phonenumbers


def normilize_phonenumber(apps, schema_editor):
    """Fills in owner_pure_phone field."""

    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone_number):
            flat.owner_pure_phone = phonenumbers.format_number(
                phone_number, phonenumbers.PhoneNumberFormat.E164)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20240303_0101'),
    ]

    operations = [
        migrations.RunPython(normilize_phonenumber),
    ]
