# Generated by Django 2.2.24 on 2024-03-03 14:38

from django.db import migrations


def create_owners(apps, sheme_editor):
    """Creates Owner objects from Flat objects."""

    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        obj, created = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone)
        obj.flats.add(flat)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(create_owners)
    ]
